### ISSUE TITLE
custom lightweight docker rultor image with rust

### ISSUE THREAD

**Issue by l3r8yJ** [h1alexbel/fakehub#11]
docker image have to contain

1. latest version of rust
2. standart unix tooling

**Comment by h1alexbel** [comment]
@l3r8yJ we also can bump versions in the origin image by submitting pr

**Comment by l3r8yJ** [comment]
@h1alexbel sure, idea is good, but original image has too many dependencies. They're just slows down pipelines

wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ yeah, let's create our lightweight version with rust only

**Comment by h1alexbel** [comment]
@l3r8yJ our current image works. However, it is very slow (almost merges and release take 20min), mostly because of the 
need to pull rust image from the scratch (Java builds take 3-5 min), and image size. Let's try to create a lightweight image for rust only, so it would be fast and convenient to work with.

**Comment by h1alexbel** [comment]
@l3r8yJ its already done: github.com/h1alexbel/rultor-rust-image
