### ISSUE TITLE
store data in PostgreSQL database

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fakehub#121]
Let's store data in PostgreSQL database instead of XML. This should simplify our flow and get rid of synchronization issues

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel i don't like this idea, because we don't need persist data during the test scenario. As far as I understand, all we need:
1. Run the tool
2. Do manipulations with data
3. Stop the tool

I would rather to have all this data in memory, it will remove all overheads from moving it to `psql` or `xml`. In addition, it would be hard to isolate test data in `psql` for each test that user will run, wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ I think we can drop all the data right after tool has been stopped. I fully agree with in-memory solution. Does any in-memory SQL database can be utilized, or you referring to some other in-memory application?

**Comment by h1alexbel** [comment]
won't do that: https://github.com/h1alexbel/fakehub/pull/123#issuecomment-2315103122
